# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
# DEV APP CONFIGURATION

client_id = "19bafcd457f52181a12054b310728aaf"
name = "occ-inventory-hub-dev"
application_url = "https://occ-inventory-hub-dev.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,write_products"

[access]
direct_api_mode = "offline"

[auth]
redirect_urls = [
  "https://occ-inventory-hub-dev.vercel.app/auth/callback",
  "https://occ-inventory-hub-dev.vercel.app/auth/shopify/callback",
  "https://occ-inventory-hub-dev.vercel.app/partner/callback"
]
